### PR TITLE
feat: Add BeautifulSoupParser type alias

### PR DESCRIPTION
**Pull request by Pijukatel**
### Description

To avoid repeating same Literal definitions.

### Checklist

- [x] CI passed

### CODE REVIEW

**Review by janbuchar — COMMENTED** [review]
Sure, this makes sense. Could you consider reexporting the new type so that you can import it without accessing private subpackages?

**Comment by Pijukatel** [comment]
> Sure, this makes sense. Could you consider reexporting the new type so that you can import it without accessing private subpackages?

Sure. Just a tiny question. What is the established practice here with __all__? I know it is for star imports, but do you put all stuff inside or just some selected top level stuff?

**Comment by janbuchar** [comment]
You should include only names that are part of the "public interface" of the package in `__all__`.

**Comment by vdusek** [comment]
I will also add that the `__all__` field is there primarily because some Python tooling uses it to discover the package's public interface.

**Comment by janbuchar** [comment]
@Pijukatel And I will add this - it's a nice read: https://mkdocstrings.github.io/griffe/guide/users/recommendations/public-apis/

**Review by janbuchar — APPROVED** [review]
LGTM

**Review by vdusek — APPROVED** [review]
LGTM

**Pull request merged**
