### PR TITLE
fix: extend from `StrEnum` in `RequestState` to fix serialization

### PR DESCRIPTION
**Pull request by vdusek**
Closes: #551

### CODE REVIEW

**Review by janbuchar — CHANGES_REQUESTED** [review]
1. let's consider if we want to keep this compatible with crawlee-js, where we store numbers
2. we could just use `IntEnum` or `(str, Enum)` - https://docs.pydantic.dev/dev/api/standard_library_types/#enum - I don't want to maintain duplicates of standard library code

**Comment by vdusek** [comment]
> let's consider if we want to keep this compatible with crawlee-js, where we store numbers

I see a slight advantage in serializing it as something more readable, like `{"state": "Unprocessed"}`, instead of using just numbers, such as `{"state": 1}`.

> we could just use IntEnum or (str, Enum) - https://docs.pydantic.dev/dev/api/standard_library_types/#enum - I don't want to maintain duplicates of standard library code

Oh, that's good, thanks.

**Comment by janbuchar** [comment]
> > let's consider if we want to keep this compatible with crawlee-js, where we store numbers
> 
> I see a slight advantage in serializing it as something more readable, like `{"state": "Unprocessed"}`, instead of using just numbers, such as `{"state": 1}`.

Yeah, I agree with that. I guess it boils down to whether we want the two formats to be compatible. Frankly, I don't see any advantage in that.

**Comment by vdusek** [comment]
> Yeah, I agree with that. I guess it boils down to whether we want the two formats to be compatible. Frankly, I don't see any advantage in that.

Ok, let's use `IntEnum` then.

**Comment by janbuchar** [comment]
> > Yeah, I agree with that. I guess it boils down to whether we want the two formats to be compatible. Frankly, I don't see any advantage in that.
> 
> Ok, let's use `IntEnum` then.

Just so we're clear, we're both OK with string values, but we're keeping the integers for the sake of compatibility, right?

**Comment by janbuchar** [comment]
Could you also incorporate the test changes from https://github.com/cadlagtrader/crawlee-python/commit/02a5c6b9b35f0573068d878b4f4367a6a1d8fbf5?

**Comment by vdusek** [comment]
> Could you also incorporate the test changes from https://github.com/cadlagtrader/crawlee-python/commit/02a5c6b9b35f0573068d878b4f4367a6a1d8fbf5?

I already implemented a new test covering this.

**Comment by janbuchar** [comment]
> > Could you also incorporate the test changes from [cadlagtrader@02a5c6b](https://github.com/cadlagtrader/crawlee-python/commit/02a5c6b9b35f0573068d878b4f4367a6a1d8fbf5)?
> 
> I already implemented a new test covering this.

Yeah, I mean just to make it clear that the reported issue is *fixed* :smile:

**Comment by B4nan** [comment]
We can change the enum in JS version to store numbers, no problems with that. Generally speaking, numbers will be more performant and less memory sensitive than strings, but we already store a lot of stuff in the request object that I doubt this can be measurable.

**Comment by janbuchar** [comment]
> We can change the enum in JS version to store numbers, no problems with that. Generally speaking, numbers will be more performant and less memory sensitive than strings, but we already store a lot of stuff in the request object that I doubt this can be measurable.

image

...apparently, that's already the case. The performance impact is most likely non-existent, yes.

**Review by janbuchar — APPROVED** [review]

**Pull request merged**
