### PR TITLE
ci: Do not run pre-release in forks

### PR DESCRIPTION
**Pull request by janbuchar**
- see discussion in https://github.com/apify/apify-client-js/pull/596#discussion_r1814782521

### CODE REVIEW

**Review by B4nan — APPROVED** [review]
how come the whole condition is a string btw?

**Comment by janbuchar** [comment]
> how come the whole condition is a string btw?

YAML programming! I guess the quotes are not really necessary, but better safe than sorry.

**Review by vdusek — APPROVED** [review]
LGTM

**Comment by B4nan** [comment]
I guess they are not, we have quite complex conditions elsewhere without them, e.g. https://github.com/apify/crawlee/blob/master/.github/workflows/test-ci.yml#L17

**Pull request merged**
