### PR TITLE
fix: Remove redundant log, fix format

### PR DESCRIPTION
**Pull request by janbuchar**

### CODE REVIEW

**Review by B4nan — APPROVED** [review]
can we add a test case for this maybe? so its clear how it looks

**Comment by janbuchar** [comment]
> can we add a test case for this maybe? so its clear how it looks

We can, but should we? It sounds both flaky and fragile...

**Comment by B4nan** [comment]
Well, I don't want any flaky tests, but you can mock everything out. My idea was a simple unit test where you log predefined stats and assert how they were logged.

**Review by B4nan — APPROVED** [review]
thats exactly what i meant 👍

**Pull request merged**
