### PR TITLE
feat(playwright): `infinite_scroll` helper

### PR DESCRIPTION
**Pull request by janbuchar**
This implements a bare bones infinite scroll helper. It is also added into the crawling context.

### CODE REVIEW

**Comment by barjin** [comment]
Why not [infinite_scroll](https://github.com/apify/crawlee/blob/master/packages/playwright-crawler/src/internals/utils/playwright-utils.ts#L396)?

(reading this on mobile, sorry if I'm missing something)

**Comment by B4nan** [comment]
Yeah, I would stay consistent with the JS version.

**Comment by janbuchar** [comment]
Sure thing, I'll change it

**Review by vdusek — APPROVED** [review]
LGTM, just we could probably make module `playwright_crawler/utils.py` private, what do u think?

**Comment by janbuchar** [comment]
> LGTM, just we could probably make module `playwright_crawler/utils.py` private, what do u think?

Not sure. OG crawlee exposes this to the public, but it doesn't include it in the context.

**Comment by B4nan** [comment]
It is included in the context

https://github.com/apify/crawlee/blob/master/packages/playwright-crawler/src/internals/utils/playwright-utils.ts#L752
https://crawlee.dev/api/playwright-crawler/interface/PlaywrightCrawlingContext#infiniteScroll

**Pull request merged**
