### PR TITLE
feat: Added get_public_url method to KeyValueStore

### PR DESCRIPTION
**Pull request by naaa760**
### Description

This pull request introduces the `get_public_url` method to the `KeyValueStore` class. This method generates a file URL for a given key, allowing for easy access to stored files. The URL is constructed dynamically based on the storage directory and store name.

### Issues

Fix: #514

### Testing

- Unit tests were added to verify the functionality of the `get_public_url` method. All existing and new tests were executed successfully to ensure no regressions.

### Checklist

- [ ] CI passed

### CODE REVIEW

**Comment by vdusek** [comment]
Hi @naaa760, you're adding almost 190k new lines of code, are you sure that's correct?

**Comment by naaa760** [comment]
> Hi @naaa760, you're adding almost 190k new lines of code, are you sure that's correct?

I Update the deployment dependencies, that's how it adds up lines of code and yeah it's right!

**Comment by belloibrahv** [comment]
The PR title does not conform to the required format. To ensure successful processing, please begin the title with a prefix indicating the type of change (e.g., `feat`, `fix`, `docs`, etc.). For example, you could modify the title to 'feat: Added get_public_url method to KeyValueStore'.

**Comment by vdusek** [comment]
> I Update the deployment dependencies, that's how it adds up lines of code and yeah it's right!

Well, certainly your PR should not include your Python environment - the env directory.

**Pull request closed without merging**
