### PR TITLE
refactor!: Update the crawlers & storage clients structure

### PR DESCRIPTION
**Pull request by vdusek**
## Description

Update the dir structure of crawlers & storage clients, as discussed earlier on the Slack.

I decided to export nothing on the 2nd level because of the extras & it would also be pretty huge (taking into account we have also models there).

E.g. for BS crawler:
```diff
- from crawlee.beautifulsoup_crawler import BeautifulSoupCrawler, BeautifulSoupCrawlingContext
+ from crawlee.crawlers import BeautifulSoupCrawler, BeautifulSoupCrawlingContext
```

Or for memory storage client:
```diff
- from memory_storage_client import MemoryStorageClient
+ from storage_clients import MemoryStorageClient
```

This should be generally more aligned with the concepts of Crawlee. Of course, quite a breaking change though. Better to do it now than later.

This will not be applied to the JS version because sub-pkgs like `PlaywrightCrawler` are its own package.

## Issue

- Closes: #764

### Crawlers & CrawlingContexts

- All crawler and crawling context classes have been consolidated into a single sub-package called `crawlers`.
- The affected classes include: `AbstractHttpCrawler`, `AbstractHttpParser`, `BasicCrawler`, `BasicCrawlerOptions`, `BasicCrawlingContext`, `BeautifulSoupCrawler`, `BeautifulSoupCrawlingContext`, `BeautifulSoupParserType`, `ContextPipeline`, `HttpCrawler`, `HttpCrawlerOptions`, `HttpCrawlingContext`, `HttpCrawlingResult`, `ParsedHttpCrawlingContext`, `ParselCrawler`, `ParselCrawlingContext`, `PlaywrightCrawler`, `PlaywrightCrawlingContext`, `PlaywrightPreNavCrawlingContext`.

Example update:
```diff
- from crawlee.beautifulsoup_crawler import BeautifulSoupCrawler, BeautifulSoupCrawlingContext
+ from crawlee.crawlers import BeautifulSoupCrawler, BeautifulSoupCrawlingContext
```

### Storage clients

- All storage client classes have been moved into a single sub-package called `storage_clients`.
- The affected classes include: `MemoryStorageClient`, `BaseStorageClient`.

Example update:
```diff
- from crawlee.memory_storage_client import MemoryStorageClient
+ from crawlee.storage_clients import MemoryStorageClient
```

### CurlImpersonateHttpClient

- The `CurlImpersonateHttpClient` changed its import location.

Example update:
```diff
- from crawlee.http_clients.curl_impersonate import CurlImpersonateHttpClient
+ from crawlee.http_clients import CurlImpersonateHttpClient
```

### CODE REVIEW

**Comment by vdusek** [comment]
I will update the upgrading guide once we definitely agreed on this. cc @pijukatel @janbuchar

**Review by Pijukatel — APPROVED** [review]

**Comment by janbuchar** [comment]
> I decided to export nothing on the 2nd level because of the extras & it would also be pretty huge (taking into account we have also models there).

I respect the reasoning behind this, but doing `from crawlee.crawlers import PlaywrightCrawler, PlaywrightCrawlingContext` would be pretty sweet. What would it take to make that possible? :grin: I'm also asking because importing from deeply nested packages could make users feel like they're reaching into the internals of the library... which is not the case.

**Comment by barjin** [comment]
Once this is done, make sure to update the Actor templates over at https://github.com/apify/actor-templates/ :) I see the Crawlee version isn't pinned there (it probably shouldn't, given the early development stage), so this will break it.

**Review by janbuchar — CHANGES_REQUESTED** [review]
- there is a failing test for importing parsel crawler
- the `crawler` template (the new, universal one) doesn't seem to be updated?

**Review by janbuchar — APPROVED** [review]

**Pull request merged**
