### PR TITLE
docs: Added [Dataset, Keystore] documentation

### PR DESCRIPTION
**Pull request by saymedgm**
### Description

- TODO

### Issues

- Closes: #TODO

### Testing

- TODO

### Checklist

- [ ] CI passed

### CODE REVIEW

**Comment by saymedgm** [comment]
can you review the PR

**Comment by MostlyKIGuess** [comment]
@saymedgm  I am not a reviewer but I think you should edit the PR content and attach the issue #479  like this, so that other people who lookup on issue see that , a PR has already been made. :)

**Review by vdusek — CHANGES_REQUESTED** [review]
It should be a guide for Crawlee Python, but your code samples are in JS. 

If you want to continue working on that, update the code samples to Python. Also, please use the same structure as we have in other guides ([docs/guides](https://github.com/apify/crawlee-python/tree/master/docs/guides)) - code samples are in separate files, we use links to API docs, ... And fill the PR description.

**Comment by janbuchar** [comment]
Closing due to inactivity

**Pull request closed without merging**
