### PR TITLE
fix: Workaround for JSON value typing problems

### LINKED ISSUE #563: Correct / recommended way of using `user_data`
After the merge of [this PR](https://github.com/apify/crawlee-python/pull/540) I receive type errors working with `user_data`. Consider this sample:

```python
import asyncio

from crawlee import Request
from crawlee._utils.urls import convert_to_absolute_url, is_url_absolute
from crawlee.configuration import Configuration
from crawlee.parsel_crawler import ParselCrawler, ParselCrawlingContext
from crawlee.router import Router

router = Router[ParselCrawlingContext]()


@router.default_handler
async def default_handler(context: ParselCrawlingContext) -> None:
    for category in context.selector.xpath(
        '//div[@class="side_categories"]//ul/li/ul/li/a'
    ):
        item = {"title": category.xpath("normalize-space()").get()}
        url = category.xpath("./@href").get()
        if url is not None:
            if not is_url_absolute(url):
                url = str(convert_to_absolute_url(context.request.url, url))
            request = Request.from_url(url, method="GET", label="detail")
            request.user_data["item"] = item  # <--- TYPE ERROR
            await context.add_requests([request])


@router.handler("detail")
async def detail_handler(context: ParselCrawlingContext) -> None:
    item = context.request.user_data["item"]
    item["results"] = context.selector.xpath("normalize-space(//form//strong[1])").get()  # <-- TYPE ERROR
    await context.push_data(item)


async def main() -> None:
    config = Configuration.get_global_configuration()
    config.persist_storage = False
    config.write_metadata = False
    crawler = ParselCrawler(request_handler=router)
    await crawler.run(["https://books.toscrape.com"])
    data = await crawler.get_data()
    print(data.items)


if __name__ == "__main__":
    asyncio.run(main())
```

Both in VS Code (with Pylance) and CLI (mypy) I get type errors on the highlighted spots. Mypy reports this:

```
./venv/bin/mypy main.py 
main.py:23: error: Incompatible types in assignment (expression has type "dict[str, str | None]", target has type "JsonValue")  [assignment]
main.py:30: error: Unsupported target for indexed assignment ("list[JsonValue] | dict[str, JsonValue] | str | bool | int | float | None")  [index]
main.py:30: error: No overload variant of "__setitem__" of "list" matches argument types "str", "str | None"  [call-overload]
main.py:30: note: Possible overload variants:
main.py:30: note:     def __setitem__(self, SupportsIndex, JsonValue, /) -> None
main.py:30: note:     def __setitem__(self, slice, Iterable[JsonValue], /) -> None
Found 3 errors in 1 file (checked 1 source file)
```

### PR DESCRIPTION
**Pull request by janbuchar**
- closes #563

@tlinhart any chance you could test this and confirm it fixes the issue?

### CODE REVIEW

**Comment by tlinhart** [comment]
@janbuchar it solves the first issue i.e. this:

```python
request.user_data["item"] = item
```

However the second issue remains:

```python
item = context.request.user_data["item"]
item["results"] = context.selector.xpath("normalize-space(//form//strong[1])").get()  <-- type error remains
```

This is what Pylance reports:

```
Metoda __setitem__ není u typu str definovánaPylance[reportIndexIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIndexIssue)
Metoda __setitem__ není u typu bool definovánaPylance[reportIndexIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIndexIssue)
Metoda __setitem__ není u typu int definovánaPylance[reportIndexIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIndexIssue)
Metoda __setitem__ není u typu float definovánaPylance[reportIndexIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIndexIssue)
Objekt typu “None“ nelze zadat jako dolní indexPylance[reportOptionalSubscript](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportOptionalSubscript)
Zadaným argumentům neodpovídají žádná přetížení pro __setitem__Pylance[reportCallIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportCallIssue)
builtins.pyi(1032, 9): Přetížení 1 je nejbližší shoda.
Argument typu Literal['results'] není možné přiřadit k parametru key typu SupportsIndex ve funkci __setitem__
  Literal['results'] není kompatibilní s protokolem SupportsIndex
    __index__ není k dispoziciPylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
(variable) item: JsonSerializable[Unknown]
```

Mypy outputs this:

```
crawlee-user_data/main.py:30: error: Unsupported target for indexed assignment ("list[Any] | dict[str, Any] | str | bool | int | float | None")  [index]
crawlee-user_data/main.py:30: error: No overload variant of "__setitem__" of "list" matches argument types "str", "str | None"  [call-overload]
crawlee-user_data/main.py:30: note: Possible overload variants:
crawlee-user_data/main.py:30: note:     def __setitem__(self, SupportsIndex, Any, /) -> None
crawlee-user_data/main.py:30: note:     def __setitem__(self, slice, Iterable[Any], /) -> None
Found 2 errors in 1 file (checked 1 source file)
```

When I try to specify a type for the `item` in

```
item: dict[str, str | None] = context.request.user_data["item"]
```

I get this type error from Pylance on the same line:

```
Typ JsonSerializable[Unknown] se nedá přiřadit k deklarovanému typu dict[str, str | None].
  Typ JsonSerializable[Unknown] se nedá přiřadit k typu dict[str, str | None].
    float se nedá přiřadit k dict[str, str | None].
```

**Comment by janbuchar** [comment]
> However the second issue remains:
> 
> ```python
> item = context.request.user_data["item"]
> item["results"] = context.selector.xpath("normalize-space(//form//strong[1])").get()  <-- type error remains
> ```

This seems correct though - `user_data["item"]` can be pretty much anything, and you're accessing it in a different function than the one you set it in, so there's really no way for the type checker to deduce the type of that item.

> When I try to specify a type for the `item` in
> 
> ```python
> item: dict[str, str | None] = context.request.user_data["item"]
> ```

This way, you say that you expect `item` to have the type `dict[str, str | None]`, but the type checker still makes sure that what you're assigning conforms to that. To convince it, you need to do this:

```python
from typing import cast
# ...
item = cast(dict[str, str | None], context.request.user_data["item"])
```

This way, you tell the type checker that you know what the type is and take full responsibility if you're wrong :slightly_smiling_face: 

I tried this locally with the relevant part of your code snippet and it seems to work. Did I miss anything?

**Comment by tlinhart** [comment]
> Did I miss anything?

No, I think you are perfectly correct ;-) Thanks!

**Review by vdusek — APPROVED** [review]
Good job, thanks

**Pull request merged**
