### PR TITLE
feat: Pass extra configuration to json.dump()

### LINKED ISSUE #526: Implement/document a way how to pass extra configuration to json.dump()
There is useful configuration to `json.dump()` which I'd like to pass through `await crawler.export_data("export.json")`, but I see no way to do that:

- `ensure_ascii` - as someone living in a country using extended latin, setting this to `False` prevents Python to encode half of the characters as weird mess
- `indent` - allows me to read the output as a mere human
- `sort_keys` - may be useful for [git scraping](https://simonwillison.net/2020/Oct/9/git-scraping/), not sure

The only workaround I can think of right now is something convoluted like:

```py
from pathlib import Path

path = Path("export.json")
await crawler.export_data(path)
path.write_text(json.dumps(json.loads(path.read_text()), ensure_ascii=False, indent=2))
```

### PR DESCRIPTION
**Pull request by Rutam21**
### Description

This PR addresses the need for customizable export configurations when using the await crawler.export_data("export.json") method.

Key Changes:

- Introduced a new option in the export_data method to accept additional keyword arguments, allowing users to pass configurations directly to `json.dump()` and other export functions.
- Created dedicated export helper methods for different formats in the `BasicCrawler`, including `export_data_json` and `export_data_csv`. This separation enhances clarity and maintainability while providing format-specific options.

This enhancement improves the flexibility of data exports, enabling users to tailor their export settings to meet specific requirements.

### Issues

Fixes #526 

### Testing

Unit test cases are added to check the updated configuration and functionality.

### Checklist

- [x] CI passed

### CODE REVIEW

**Comment by Rutam21** [comment]
This PR is based on all the discussions in the parent issue and the suggestions thereafter. Please review and suggest changes, if any. Thank you.

cc: @vdusek @janbuchar

**Review by vdusek — CHANGES_REQUESTED** [review]
Make sure the CI passes, see the [CONTRIBUTING.md](https://github.com/apify/crawlee-python/blob/master/CONTRIBUTING.md) for more information.

**Review by janbuchar — CHANGES_REQUESTED** [review]
The CI is still failing, can you please fix the issues?

**Comment by Rutam21** [comment]
@janbuchar I will push a commit to fix some of them by EOD.

**Comment by janbuchar** [comment]
@Rutam21 thank you for your initiative, but we decided to just fix up #580 on our own and merge that.

**Pull request closed without merging**
